### ISSUE TITLE
show next change (g; / g,)

### ISSUE THREAD

**Issue by marconetto** [inkarkat/vim-EnhancedJumps#3]
I really like the message to show the next jump using c-o and c-i.  It seems this plugin also has some functionality around the change list/commands (g;/g,).  I'm wondering if there is a way to show the next change line using g;/g, similar to c-o/c-i.

**Comment by inkarkat** [comment]
Thanks for the feedback; that's indeed a valuable enhancement, and easily implementable through the existing plugin functionality.
