### ISSUE TITLE
Improve installation instructions

### ISSUE THREAD

**Issue by yuriescl** [inkarkat/vim-EnhancedJumps#4]
This plugin does not work without https://github.com/inkarkat/vim-ingo-library, so https://github.com/inkarkat/vim-ingo-library, so the dependency note should be at the top of the readme to make it easy for users to know about it.

**Comment by yuriescl** [comment]
Maybe just adding instructions at the top of `README.md` regarding the dependency is sufficient, since dependency management doesn't seem to be widely supported by vim plugin managers.

**Comment by inkarkat** [comment]
Junegunn, the author of _vim-plug_, has experimented with plugin dependency information, but eventually decided against it, and documented the problems of consistent Vim plugin dependency management in [this writeup](https://junegunn.kr/2013/09/thoughts-on-vim-plugin-dependency).

I think we have to live with the manual, documentation-only way of plugin dependencies for now. Fortunately, dependencies are not used pervasively; most of my own plugins only require the _ingo-library_, so it's not a massive manual task, anyway.

I have the feeling that no matter where I put the dependency instructions, some people will just miss them, anyway. I think there're now at the right place in the [dependencies](https://github.com/inkarkat/vim-EnhancedJumps#dependencies) section. For those who don't read the documentation and then open a GitHub issue to complain, the top item in the template's FAQ points them to the problem:

* **E117: Unknown function: ingo#...**: Have you installed the [ingo-library plugin](http://www.vim.org/scripts/script.php?script_id=4433) (or via [GitHub](https://github.com/inkarkat/vim-ingo-library)) as well, as documented in the _dependencies_ section of the readme and plugin help?
